version: '3.7'

services:
  consul:
    image: consul
    ports:
      - 8500:8500

  backend:
    build:
      context: ./backend
    deploy:
      replicas: 1
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul

  client:
    build:
      context: ./client
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    ports:
    - 8090:8090